### ISSUE TITLE
The "express" dependency was not found. Did you install "express" it in your source folder via npm.

### ISSUE THREAD

**Issue by benalexb** [serverless-components/express#14]
Hello dear friends,

I was hoping that maybe you could give me a clue as to what I am doing wrong. I deviated from using the template app as I wanted to try this solution on a more realistic use case: deploying an existing express app to AWS lambda. From the original REST API I created just to test this out, the only changes I really had to make in order to have things similar to the template app were

- Decouple HTTP server and express app (such that there is an `app.js` that exports the express app)
- Added webpack to bundle the app and make it smaller

The bundle goes to `./build` containing two files (1) `app.js` and (2) `server.js`, the latter being irrelevant for what we are trying to accomplish.

As the title shows, when I hit the endpoint after deploying it, I get the following response `The "express" dependency was not found. Did you install "express" it in your source folder via npm.`

On the AWS Lambda editor, inspecting the code that was deployed, I can see where this response comes from

<img width="1261" alt="Screenshot 2020-06-02 at 13 18 30" src="https://user-images.githubusercontent.com/3350185/83514280-a2868100-a4d3-11ea-9529-abdc6c19d299.png">

App.js
```javascript
import 'regenerator-runtime/runtime'
import bodyParser from 'body-parser'
import cookieParser from 'cookie-parser'
import cors from 'cors'
import express from 'express'
import morgan from 'morgan'
import router from './router'

const app = express()
const isProduction = process.env.NODE_ENV === 'production'

// App setup
app.use(morgan(isProduction ? 'combined' : 'dev'))
app.use(cors())
app.use(cookieParser())
app.use(bodyParser.json({ type: '*/*' }))
router(app)

export default app
```
serverless.yml
```yml
component: express
name: express-api
stage: dev

inputs:
  description: fine-sifter-server-REST
  region: eu-central-1
  env:
    DEBUG: 'express:*'
    DB_CONN: (...)
    CLIENT_SECRET: (...)
  src:
    src: ./
    hook: npm run build:local
    dist: ./build
```

webpack.config.js
```javascript
const path = require('path')
const nodeExternals = require('webpack-node-externals')

module.exports = {
  entry: {
    app: './src/app.js',
    server: './src/server.js'
  },
  mode: process.env.NODE_ENV,
  target: 'node',
  externals: [nodeExternals()],
  output: {
    libraryTarget: 'commonjs',
    path: path.resolve(__dirname, 'build'),
    filename: '[name].js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [['env', { targets: { node: '12.17' } }]]
            }
          }
        ]
      }
    ]
  }
}
```

package.json
```json
{
  "name": "fine-sifter-server-rest",
  "version": "0.0.1",
  "description": "",
  "author": "Benjamin Alexandre de Macedo Barreto",
  "license": "ISC",
  "main": "src/index.js",
  "engines": {
    "node": ">=12.17.0",
    "npm": ">=6.14.5"
  },
  "scripts": {
    "build": "NODE_ENV=production webpack",
    "build:local": "env-cmd -f env-prod.env webpack",
    "start": "node build/server.js",
    "dev": "env-cmd -f env-dev.env nodemon --exec babel-node src/server.js",
    "dev:docker": "env-cmd -f env-docker-dev.env nodemon --exec babel-node src/server.js",
    "docker:dev": "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build",
    "docker:prod": "",
    "db:up": "docker-compose up --build -d",
    "db:down": "docker-compose down",
    "db:seed": "babel-node src/db-tools/seed.js"
  },
  "devDependencies": {
    "@babel/cli": "^7.10.1",
    "@babel/core": "^7.10.2",
    "@babel/node": "^7.10.1",
    "@babel/preset-env": "^7.10.2",
    "babel-loader": "^8.1.0",
    "babel-preset-env": "^1.7.0",
    "env-cmd": "^10.1.0",
    "nodemon": "^2.0.4",
    "regenerator-runtime": "^0.13.5",
    "serverless": "^1.71.3",
    "standard": "^14.3.4",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "faker": "^4.1.0",
    "jwt-simple": "^0.5.6",
    "lodash": "^4.17.15",
    "mongoose": "^5.9.16",
    "morgan": "^1.10.0",
    "passport": "^0.4.1",
    "passport-jwt": "^4.0.0",
    "passport-local": "^1.0.0"
  },
  "nodemonConfig": {
    "ignore": [
      "dist",
      "node_modules"
    ]
  },
  "standard": {
    "parser": "babel-eslint",
    "ignore": [
      ".dist",
      "node_modules"
    ]
  }
}
```

**Comment by eahefnawy** [comment]
Thanks for the detailed issue @benalexb . This error is triggered if the express module was not found in `node_modules`, which basically means you did not run `npm i` inside the source directory before deploying.

From the image, it seems that you did, but could you double-check to make sure you have the express module inside `node_modules` as expected by the handler? if you do, then there could be something wrong with detection logic we are using.

**Comment by benalexb** [comment]
Hey @eahefnawy, do you mean the source directory of my express app? Indeed I sure did, otherwise, webpack won't build/bundle the app (it fails very quickly complaining about missing dependencies).

Inspecting the deployed `handler.js` in _expresss, it looks like express is being imported on the context of the`_express` folder, but its node_moduels does not have express.
![Screenshot 2020-06-03 at 08 01 21](https://user-images.githubusercontent.com/3350185/83601343-b59b5e80-a570-11ea-9baf-c11068180426.png)

What puzzles me is that the template app works fine. The only real difference is that the template app is not being bundled using webpack, whereas in my case, we are deploying from './build' which contains just two files and no node_modules (dependencies included as externals, embedded within the chunks).

I've tried removing `hook` and `dist` from the `src` entry in `serverless.yml` just to test it, but the app is too big to be deployed that way (source is over 200mb without bundling).

🤷🏻‍♂️ 🤯 🥺

**Comment by austencollins** [comment]
@eahefnawy is this error breaking webpack builds because there is no `node_modules` folder?  If so, we should remove this error logic ASAP.

**Comment by eahefnawy** [comment]
@ac360 @benalexb hmm yeah, the require here might be causing the issue with webpack:

https://github.com/serverless-components/express/blob/master/src/_express/handler.js#L4-L11

I'll remove it asap, then we can try again.

**Comment by eahefnawy** [comment]
@benalexb I just published a patch `1.0.10` that I think should fix this issue. Could you try it out and confirm that it works? Please make sure you use this version in the yml file:

```yml
# serverless.com

component: express@1.0.10
```

or just the latest

```yml
# serverless.com

component: express
```

**Comment by benalexb** [comment]
Hi @eahefnawy, thank you for the update. I can confirm that I no longer get the error! Thank you!

**Comment by eahefnawy** [comment]
Awesome! Thanks for reporting.

**Comment by ramkrishnakuldeep** [comment]
> Hi @eahefnawy, thank you for the update. I can confirm that I no longer get the error! Thank you!

Could you help me to fix the error.
I am getting the same error

**Comment by eahefnawy** [comment]
@ramkrishnakuldeep if you have run `npm install` already, could you make sure you're using the latest version of the express component? How does your config look like?

**Comment by ramkrishnakuldeep** [comment]
> @ramkrishnakuldeep if you have run `npm install` already, could you make sure you're using the latest version of the express component? How does your config look like?

Thanks for your reply.
But I moved from serverless.yml to serverless.ts, so I don't have this error but have another one

![Screen Shot 2021-01-05 at 2 56 59 PM](https://user-images.githubusercontent.com/30339561/103615849-48b4d080-4f66-11eb-8d85-b368a827ddad.png)

![Screen Shot 2021-01-05 at 2 58 54 PM](https://user-images.githubusercontent.com/30339561/103616041-a9dca400-4f66-11eb-9d78-05c6138205d4.png)

![Screen Shot 2021-01-05 at 3 00 28 PM](https://user-images.githubusercontent.com/30339561/103616099-c4af1880-4f66-11eb-92c0-42b6c5cdea75.png)

If you could help me with it
