### ISSUE TITLE
Cookies in lambda integration payload v2

### ISSUE THREAD

**Issue by eddeee888** [serverless-components/express#16]
## Overview

Hello! I have an express app that handles sessions by using cookies. Pretty standard stuff, something like this:

```
import cookieParser from "cookie-parser";

const server = express();
server.use(cookieParser());
```
## Problem
When I try to deploy using `serverless` and this component, it works ( btw love how simple everything is! ). However, my cookies are not forwarded to the server correctly. 

## Investigation

I spent a bit of time looking through documentations ( and a lot of head scratching / hair pulling ), this is what I found:

- [payload format version 2](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) seems to extract cookies from headers automatically and put it in `cookies` field on the event

- Since `aws-serverless-express` currently supports v1, we do a small [conversion here](https://github.com/serverless-components/express/blob/b06776d3635b01737d1dd3ddab5f102a3b39e9c1/src/_express/handler.js#L11-L13) to make sure that the shape matches. However, the cookies are no longer in the headers so it never gets forwarded to the backend.

## Proposed solution

I think in the [conversion section of the handler](https://github.com/serverless-components/express/blob/b06776d3635b01737d1dd3ddab5f102a3b39e9c1/src/_express/handler.js#L9-L13), we should put back the `cookies` into the `headers` field.

## How to replicate

- create a new project per documentation
- use Insomnia to send a request to the endpoint with a cookie
- `cookie` is not in headers ( However, if you decode URI component in `x-apigateway-event`, you'll be able to see the `cookies` field separate from `headers`. Because `aws-serverless-express` [keeps the encoded original apigateway event](https://github.com/awslabs/aws-serverless-express/blob/ac6ebd1e9faacbe0381b66d06ece6aa72d0cd007/src/index.js#L41-L66) )
- if we go to api gateway and change the payload integration to v1, remove the conversion code in the deployed lambda, wire up the api gateway with the new lambda, we'll be able to see `cookie` in the headers because v1 just forwards everything

Hopefully this makes sense. Maybe thre's another way around this and I haven't pulled my hair hard enough to figure it out :)

**Comment by eahefnawy** [comment]
@eddeee888 your solution is perfect! Care to submit a PR? 😊 

Otherwise, I'd be happy to do it as soon as I can 🙌

**Comment by eddeee888** [comment]
@eahefnawy I can give this a go! Will let you know how I go 😄
