### ISSUE TITLE
How to connect to external database?

### ISSUE THREAD

**Issue by sean-hill** [serverless-components/express#6]
Hi!

I used to connect to my external databases such as SQL or Mongo outside of the handler function of my previous lambda functions so that the connection was shared between subsequent function calls. Now that I don't have access to my own handler function anymore with this component, what would be the best way to do that?

**Comment by eahefnawy** [comment]
That's an interesting use case 🤔 .... do you think if we required the `app.js` file outside the handler it would solve your issue?
https://github.com/serverless-components/express/blob/master/src/_express/handler.js#L15

**Comment by sean-hill** [comment]
@eahefnawy I think I might be able to do some logic in my "connect" code that just says, if a DB connection has been previously established, to not reconnect again. So overtime the lambda is called, only on a cold start will it connect to my database. I think that should work. I'll close this out for now :)

**Comment by eahefnawy** [comment]
Cool. Thanks for letting me know 😊
