### ISSUE TITLE
"Dev" mode is failing to capture "UnhandledPromiseRejection" errors with `sls dev` mode

### ISSUE THREAD

**Issue by austencollins** [serverless-components/express#7]
`sls dev` is failing to capture and report `UnhandledPromiseRejection` errors w/ the Express Component.

This must have something to do with the Express wrapper/packaging.

Recreate:

```javascript
app.get(`/*`, async (req, res) => {
  await someBrokenPromise()
})

// Error handler
app.use((err, req, res, next) => {
  console.error(err)
  res.status(500).send('Internal Serverless Error')
})
```

Nothing will show up in the `sls dev` mode CLI output.  However, the error is in CloudWatch, clearly labeled 'UnhandledPromiseRejection' error.

Express.js users can fix this by writing proper Express.js error handling techniques.  

```javascript
app.get(`/*`, async (req, res, next) => {
  try {
    await someBrokenPromise()
  } catch(error) {
    return next(error)
  }
})

// Error handler
app.use((err, req, res, next) => {
  console.error(err)
  res.status(500).send('Internal Serverless Error')
})
```

It's just not acceptable for us that something shows up in CloudWatch, but not in `dev` mode :(

**Comment by eahefnawy** [comment]
fixed!
